import { MigrationInterface, QueryRunner } from "typeorm";

export class Uzchess1778502497332 implements MigrationInterface {
    name = 'Uzchess1778502497332'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "otpcodes" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "otpcodes" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "otpcodes" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "otpcodes" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "souvenir-image" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "souvenir-image" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "souvenir-image" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "souvenir-image" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "color" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "color" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "color" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "color" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "souvenirColor" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "souvenirColor" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "souvenirColor" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "souvenirColor" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "souvenirs" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "souvenirs" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "souvenirs" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "souvenirs" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "souvenir-review" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "souvenir-review" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "souvenir-review" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "souvenir-review" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "souvenir-likes" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "souvenir-likes" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "souvenir-likes" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "souvenir-likes" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reportCategories" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "reportCategories" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reportCategories" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "reportCategories" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "news" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "news" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "news" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "news" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "newsViews" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "newsViews" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "newsViews" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "newsViews" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coursecategories" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "coursecategories" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coursecategories" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "coursecategories" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "languages" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "languages" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "languages" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "languages" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coursesections" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "coursesections" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coursesections" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "coursesections" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "author" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "author" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "author" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "author" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "courseLikes" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "courseLikes" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "courseLikes" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "courseLikes" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "courseLesson" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "courseLesson" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "courseLesson" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "courseLesson" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "difficulties" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "difficulties" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "difficulties" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "difficulties" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "bookcategory" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "bookcategory" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "bookcategory" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "bookcategory" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "bookLikes" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "bookLikes" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "bookLikes" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "bookLikes" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "books" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "books" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "bookReviews" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "bookReviews" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "bookReviews" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "bookReviews" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users_lessons" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "users_lessons" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users_lessons" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "users_lessons" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "purchasedCourses" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "purchasedCourses" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "purchasedCourses" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "purchasedCourses" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "courseReviews" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "courseReviews" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "courseReviews" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "courseReviews" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "countries" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "countries" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "countries" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "countries" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "players" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "players" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "players" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "players" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "cart_items" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "players" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "players" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "players" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "players" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "matches" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "matches" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "countries" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "countries" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "countries" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "countries" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "courseReviews" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "courseReviews" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "courseReviews" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "courseReviews" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "purchasedCourses" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "purchasedCourses" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "purchasedCourses" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "purchasedCourses" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users_lessons" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "users_lessons" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users_lessons" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "users_lessons" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "bookReviews" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "bookReviews" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "bookReviews" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "bookReviews" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "books" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "books" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "books" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "bookLikes" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "bookLikes" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "bookLikes" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "bookLikes" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "bookcategory" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "bookcategory" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "bookcategory" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "bookcategory" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "difficulties" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "difficulties" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "difficulties" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "difficulties" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "courseLesson" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "courseLesson" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "courseLesson" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "courseLesson" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "courses" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "courses" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "courseLikes" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "courseLikes" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "courseLikes" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "courseLikes" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "author" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "author" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "author" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "author" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coursesections" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "coursesections" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coursesections" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "coursesections" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "languages" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "languages" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "languages" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "languages" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coursecategories" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "coursecategories" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "coursecategories" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "coursecategories" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "newsViews" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "newsViews" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "newsViews" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "newsViews" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "news" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "news" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "news" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "news" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reportCategories" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "reportCategories" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reportCategories" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "reportCategories" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "souvenir-likes" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "souvenir-likes" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "souvenir-likes" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "souvenir-likes" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "souvenir-review" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "souvenir-review" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "souvenir-review" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "souvenir-review" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "souvenirs" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "souvenirs" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "souvenirs" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "souvenirs" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "souvenirColor" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "souvenirColor" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "souvenirColor" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "souvenirColor" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "color" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "color" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "color" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "color" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "souvenir-image" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "souvenir-image" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "souvenir-image" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "souvenir-image" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "otpcodes" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "otpcodes" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "otpcodes" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "otpcodes" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
    }

}
